// Bundles each MCP App view (ui/<view>/app.ts, MCP Apps SDK included) into a single
// self-contained HTML string, so the sandboxed frame loads no script from a CDN.
// Output: src/ui/generated/<view>.ts (gitignored), imported by the server.
// Runs before build, build:vercel, typecheck and test.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { build } from "esbuild";

const VIEWS = [{ name: "property-card", exportName: "PROPERTY_CARD_HTML" }];
const MARKER = "<!-- APP_SCRIPT -->";

await mkdir("src/ui/generated", { recursive: true });
for (const view of VIEWS) {
  const result = await build({
    entryPoints: [`ui/${view.name}/app.ts`],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none",
    write: false,
  });
  const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
  const template = await readFile(`ui/${view.name}/index.html`, "utf8");
  if (!template.includes(MARKER)) throw new Error(`ui/${view.name}/index.html is missing ${MARKER}`);
  // A replacer function keeps `$&`-style sequences in the minified JS literal.
  const html = template.replace(MARKER, () => `<script type="module">${js}</script>`);
  await writeFile(
    `src/ui/generated/${view.name}.ts`,
    `// Generated by scripts/build-ui.mjs from ui/${view.name}/. Do not edit.\nexport const ${view.exportName} = ${JSON.stringify(html)};\n`,
  );
  console.log(`ui: ${view.name} ${(html.length / 1024).toFixed(0)} KB`);
}
